checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
        config_file: .pylintrc
build:
    environment:
        python: 3.5.0
    dependencies:
        before:
            - pip install -r requirements.txt
filter:
    excluded_paths:
        - 'tests/*'
